### ISSUE TITLE
Split these into two options?

### ISSUE THREAD

**Issue by kessler** [ironSource/node-generator-nom#6]
![image](https://cloud.githubusercontent.com/assets/147367/10618244/87e83070-7777-11e5-95ea-16c5f5a08b45.png)

Perhaps "Install gulp" and "setup es6 gulp file" should be split?

**Comment by vweevers** [comment]
It could be worded better, but why split it? What good is gulp without a gulpfile, and vice versa?

**Comment by kessler** [comment]
I meant, someone might want an es5 gulpfile...

**Comment by vweevers** [comment]
Ah, of course. Still, splitting into "Install gulp" and "setup es6 gulp file" doesn't make sense, because an ES6 gulpfile requires additional dependencies. But we could do this:

Rename "Install gulp and setup ES6 gulpfile" to "Create gulpfile". If selected, ask for es6 or es5.
- If ES6: copy templates `gulpfile.babel.js` and `.babelrc`, install gulp and babel-core
- If ES5: copy template `gulpfile.js`, install gulp

**Comment by kessler** [comment]
sounds perfect!
